### ISSUE TITLE
Multiple Samples At Once

### ISSUE THREAD

**Issue by peflanag** [raymondkiu/fastq_info#2]
Hi @raymondkiu I'm really keen to try your coverage script and was wondering can multiple samples be run at the same time using a loop?

I must be upfront and say I'm new to the world of scripts/command so I'm not that savvy! Normally for writing a loop I do something like this:

1  #!/bin/sh
2 
3  sampleLoc=/Path/to/fq.gz/
4  sampleName= ("19IE01" "19IE02" "19IE03" "19IE04" "19IE05" )
5  outputLoc=/Path/to/Output/
6
7  for sample in ${sampleName[*]}
8 
9  do
10
11  spades.py -1 $sampleLoc/${sample}*R1*.fq.gz -2 $sampleLoc/${sample}*R2*.fq.gz -o 
     $outputLoc/${sample}
12
13  done

Can I add something similar to the ./fastq_info_3.sh file to loop all the .fq.gz files?

Cheers

**Comment by raymondkiu** [comment]
Hi @peflanag 

This simple script is a shell script so should be able to run the loops like what you described although I tend to run it in a different way but loops are loops there are many ways to do the same thing.

Remember this script is taking positional arguments, get ready your paired-end fastq and fasta assembly if you want to run fastq_info_3.sh and run like below (in the same working directory otherwise you will need to specify the paths):

$ ./fastq_info_3.sh FILE1.fastq FILE2.fastq FILE3.fasta

Try one or two files first before running hundreds of files in one go just in case anything goes wrong, let me know if you still have problems running it.

Thanks,
Raymond

**Comment by peflanag** [comment]
Cheers for the quick reply. So i tried it on one file first. I used SPAdes to assemble and then I cd into the folder where fastq_info_3.sh was and pointed to the directories where the R1, R2 and fasta where and it worked. Im just curious as to where I write my script above into your script without ruining your script! Simple put I dont understand your script when I read it! I'm very much a novice! 

your first line is fastq1=$1 and fastq2=$2 but if my samples are fq.gz does that mater and if i put the names in like the sampleName above how does that affect your script?

I hope I am making sense!

**Comment by peflanag** [comment]
Actually, I am not sure it is working cause im getting 0 coverage back for each sample I run! Do the assembled.fasta files have to be called the same as the R1 and R2 input? Spades just pumps out a folder named the same buy the fasta in there is just called contigs.fasta

**Comment by raymondkiu** [comment]
Sorry @peflanag have not been monitoring so only saw it just now. Did you manage to run it?

**Comment by peflanag** [comment]
Hi, 

I never got it to work. However, for my TB samples the program MTBseq gives me coverage which is fine. I wanted to use this program for teh odd time I look at other species that I don't run with MTBseq

**Comment by raymondkiu** [comment]
@peflanag this is odd though as it is a simple script just counting the lines (reads) and simple maths to work out the coverage. So you got 0 for all runs?

**Comment by raymondkiu** [comment]
@peflanag I have fixed the problem should run smoothly now with v2.0.

**Comment by peflanag** [comment]
Oh amazing! Thanks @raymondkiu I really appreciate this!
